name: keiko_app
description: >-
  Keiko - A decentralized educational social network (DApp) built on Substrate that transforms learning into verifiable human capital. 
  Features a Life Learning Passport system with atomic learning interactions (xAPI compatible), decentralized LRS, 
  AI tutoring integration, and a keikoin-based educational economy.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.1.0

  # Networking & Blockchain
  dio: ^5.0.0
  web3dart: ^3.0.1
  polkadot_dart: ^4.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Video Calling (For tutoring)
  jitsi_meet_flutter_sdk: ^11.4.0
  agora_rtc_engine: ^6.2.2

  # UI Components
  timeline_tile: ^2.0.0
  cristalyse: ^1.0.0

  # Authentication & Security
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.1.6

  # Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^3.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Push Notifications
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

  # Analytics & Monitoring
  firebase_analytics: ^12.0.0
  sentry_flutter: ^9.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.6
  injectable_generator: ^2.1.0
  json_serializable: ^6.7.1
  freezed: ^3.1.0

  # Testing
  mockito: ^5.4.2
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter

  # Analysis & Linting
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0

  # Documentation
  dartdoc: 8.3.4

flutter:
  uses-material-design: true
