name: keiko_app
description: >-
  Keiko - A decentralized educational social network (DApp) built on Substrate that transforms learning into verifiable human capital. 
  Features a Life Learning Passport system with atomic learning interactions (xAPI compatible), decentralized LRS, 
  AI tutoring integration, and a keikoin-based educational economy.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.1.0
  
  # Networking & Blockchain
  dio: ^5.0.0
  web3dart: ^2.7.1
  polkadot_dart: ^1.0.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Video Calling (For tutoring)
  jitsi_meet_flutter_sdk: ^0.1.0
  agora_rtc_engine: ^6.2.2
  
  # UI Components
  flutter_timeline: ^1.0.0
  timeline_tile: ^2.0.0
  charts_flutter: ^0.12.0
  
  # Authentication & Security
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.6
  
  # Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # Push Notifications
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  
  # Analytics & Monitoring
  firebase_analytics: ^10.4.5
  sentry_flutter: ^7.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  injectable_generator: ^2.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  integration_test:
    sdk: flutter
    
  # Analysis & Linting
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.5
  very_good_analysis: ^5.0.0
  
  # Documentation
  dartdoc: ^6.3.0

flutter:
  uses-material-design: true
