# Cargo configuration for Windows development
# 
# PATCH WARNINGS ON WINDOWS:
# The warnings about tikv-jemalloc-sys and librocksdb-sys patches not being used
# are expected on Windows. These patches are for Linux optimization only.
#
# To suppress warnings during testing, use:
# cargo test [args] 2>$null        (PowerShell)
# cargo test [args] 2>nul          (CMD)
# Or use the provided test-quiet.ps1 script

[build]
# Windows-specific build configuration
target-dir = "target-windows"